# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "/"  # Include trailing slash
# title = "ygerber"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright Â© 2022-2024, Y.Gerber & Authors"
# canonifyurls = true
theme = "hugo-clarity"
DefaultContentLanguage = "en"
timeout = 30000
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[pagination]
  pagerSize = 10

[services]
  [services.disqus]
    shortname = ""

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
