[goldmark]
  [goldmark.renderer]
    hardWraps = false
    unsafe = true # change to false to disable inclusion of rawHTML and math functions
    xhtml = false
  [goldmark.extensions]
    typographer = false

[highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = "--"
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = false
  # style = "monokai"
  tabWidth = 2
