#[[main]]
# name = "Home"
#  url = ""
#  weight = -115

[[main]]
  name = "VMware"
  identifier = "vmware"
  url = "tags/vmware"
  weight = -114
[[main]]
  parent = "vmware"
  name = "vSphere"
  url = "tags/vsphere"
  weight = 1
[[main]]
  parent = "vmware"
  name = "vSAN"
  url = "tags/vsan"
  weight = 2
[[main]]
  parent = "vmware"
  name = "VKS"
  url = "tags/vsphere-kubernetes-service"
  weight = 3
[[main]]
  parent = "vmware"
  name = "VCF"
  url = "tags/vcf"
  weight = 4
[[main]]
  parent = "vmware"
  name = "vCenter"
  url = "tags/vcenter"
  weight = 5

[[main]]
  name = "K8s"
  url = "tags/kubernetes"
  weight = -113

[[main]]
  name = "Networking"
  url = "tags/networking/"
  weight = -109

# Submenus are done this way: parent -> identifier
#[[main]]
# name = "Links"
#  identifier = "Links"
#  weight = -108
#[[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/in/yannick-gerber-2807921a9/"
#[[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/y_gerber"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/varmox"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/y_gerber"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/yannick-gerber-2807921a9/"


# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"